### ISSUE TITLE
Base project structure for placeholder

### ISSUE THREAD

**Issue by saxumVermes** [district13labs/mcs2lm#2]
### Context
**As a developer I want to have a basic project structure so that it could serve as a placeholder for the application's environment.**
This will ease the construction of the local development environment and the surrounding elements including ci/cd integration.
### Acceptance criteria
Include the following:
- .gitignore
- makefile
- application entrypoint
- go module and related components
- basic folder structure (internal - with main.go, src, test, doc)
- an example test
- Readme.md
### Technical recommendation
This ticket is a prerequisite for upcoming tickets.

**Comment by herczogzoltan** [comment]
Closes #6
